# Generated by Django 5.2 on 2025-04-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_materia', models.CharField(max_length=100)),
                ('horas', models.CharField(max_length=10)),
                ('minutos', models.CharField(max_length=10)),
                ('segundos', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_metas', models.CharField(max_length=100)),
                ('horas_meta', models.CharField(max_length=10)),
                ('minutos_meta', models.CharField(max_length=10)),
                ('segundos_meta', models.CharField(max_length=10)),
            ],
        ),
    ]
