<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-04-25 02:06

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2 on 2025-04-28 19:10

>>>>>>> 77740e6 (back dos lembretes)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTime', '0001_initial'),
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 77740e6 (back dos lembretes)
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
>>>>>>> 77740e6 (back dos lembretes)
            ],
        ),
    ]
