# Generated by Django 5.1.7 on 2025-04-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_metas', models.CharField(max_length=100)),
                ('horas_meta', models.IntegerField()),
                ('minutos_meta', models.IntegerField()),
                ('segundos_meta', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='materia',
            name='horas_meta',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='minutos_meta',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='segundos_meta',
        ),
    ]
