# Generated by Django 5.1.7 on 2025-05-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTime', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataD',
        ),
    ]
