# Generated by Django 5.1.7 on 2025-04-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTime', '0002_meta_remove_materia_horas_meta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='hora_materia',
            field=models.IntegerField(default=0),
        ),
    ]
