# Generated by Django 5.1.7 on 2025-05-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTime', '0002_delete_datad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorMateria',
            fields=[
                ('materia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FocusTime.materia')),
                ('cor', models.CharField(default='#9A9A9A', max_length=7)),
            ],
        ),
    ]
