# Generated by Django 5.1.7 on 2025-04-06 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTime', '0003_materia_hora_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='hora_materia',
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('pause_time', models.DateTimeField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FocusTime.materia')),
            ],
        ),
    ]
