# Generated by Django 5.1.7 on 2025-04-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FocusTime', '0004_remove_materia_hora_materia_tempo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tempo',
        ),
    ]
